import { X, ChartLineUp, TrendUp, TrendDown, Package, FilePdf, WhatsappLogo } from "@phosphor-icons/react";
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerBody,
} from "@/components/ui/drawer";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useMediaQuery } from "@/lib/use-media-query";
import { Button } from "@/components/ui/button";
import type { WeeklyReportResponse, DailySalesEntry } from "@/lib/endpoints";

interface ReportsDrawerProps {
  open: boolean;
  onClose: () => void;
  weeklyData: WeeklyReportResponse | null;
}

const DAY_NAMES: Record<string, string> = {
  M: "Monday", T: "Tuesday", W: "Wednesday",
  F: "Friday", S: "Sunday",
};

function dayName(day: string) {
  if (day === "T") return "Tuesday";
  if (day === "S") return "Sunday";
  return DAY_NAMES[day] || day;
}

export interface ReportSummary {
  revenue: number;
  profit: number;
  fastestSelling: WeeklyReportResponse["fastest_selling"];
  dailySales: DailySalesEntry[];
  lowStock: WeeklyReportResponse["low_stock_items"];
  maxAmount: number;
  bestDay: DailySalesEntry | undefined;
  slowestDay: DailySalesEntry | undefined;
  profitMargin: number;
  shareUrl: string;
}

export function summarizeWeeklyReport(weeklyData: WeeklyReportResponse | null): ReportSummary {
  const revenue = weeklyData?.revenue ?? 0;
  const profit = weeklyData?.profit ?? 0;
  const fastestSelling = weeklyData?.fastest_selling ?? null;
  const dailySales = weeklyData?.daily_sales ?? [];
  const lowStock = weeklyData?.low_stock_items ?? [];
  const maxAmount = Math.max(...dailySales.map((d) => d.amount), 1);
  const bestDay = dailySales.reduce<DailySalesEntry | undefined>((best, d) => !best || d.amount > best.amount ? d : best, undefined);
  const slowestDay = dailySales.reduce<DailySalesEntry | undefined>((slow, d) => !slow || d.amount < slow.amount ? d : slow, undefined);
  const profitMargin = revenue > 0 ? Math.round((profit / revenue) * 100) : 0;

  const shareMessage =
    `*Weekly Report — Traka*\n\n` +
    `Revenue: ₦${revenue.toLocaleString()}\n` +
    `Profit: ₦${profit.toLocaleString()}\n` +
    (fastestSelling ? `Top Seller: ${fastestSelling.product_name}\n` : "") +
    `\nGenerated by Traka — Smart Bookkeeping`;

  return {
    revenue,
    profit,
    fastestSelling,
    dailySales,
    lowStock,
    maxAmount,
    bestDay,
    slowestDay,
    profitMargin,
    shareUrl: `https://wa.me/?text=${encodeURIComponent(shareMessage)}`,
  };
}

/**
 * Weekly report: right-docked sheet on desktop, bottom drawer on mobile.
 * Both shells render the same body + footer around their own header.
 */
export function ReportsDrawer({
  open,
  onClose,
  weeklyData,
}: ReportsDrawerProps) {
  const isDesktop = useMediaQuery("(min-width: 1024px)");
  const summary = summarizeWeeklyReport(weeklyData);

  if (isDesktop) {
    return (
      <Sheet open={open} onOpenChange={(o) => !o && onClose()}>
        <SheetContent side="right" showCloseButton={false} className="gap-0 p-0">
          <SheetHeader className="flex-row items-center justify-between gap-2 border-b border-border px-5 py-4">
            <SheetTitle className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-primary">
              <ChartLineUp weight="fill" className="h-4 w-4" />
              Weekly Reports &amp; Insights
            </SheetTitle>
            <Button
              type="button"
              variant="ghost"
              size="icon-sm"
              onClick={onClose}
              aria-label="Close weekly report"
              className="text-muted-foreground"
            >
              <X weight="bold" className="h-4 w-4" />
            </Button>
          </SheetHeader>
          <div className="min-h-0 flex-1 overflow-y-auto px-5 py-4">
            <WeeklyReportBody summary={summary} />
          </div>
          <div className="border-t border-border px-5 py-4">
            <WeeklyReportFooter summary={summary} />
          </div>
        </SheetContent>
      </Sheet>
    );
  }

  return (
    <Drawer open={open} onOpenChange={(o) => !o && onClose()}>
      <DrawerContent>
        <DrawerHeader>
          <DrawerTitle className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-primary">
            <ChartLineUp weight="fill" className="h-4 w-4" />
            Weekly Reports &amp; Insights
          </DrawerTitle>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            onClick={onClose}
            aria-label="Close weekly report"
            className="text-muted-foreground"
          >
            <X weight="bold" className="h-4 w-4" />
          </Button>
        </DrawerHeader>
        <DrawerBody>
          <WeeklyReportBody summary={summary} />
        </DrawerBody>
        <div className="border-t border-border px-5 py-4 pb-8">
          <WeeklyReportFooter summary={summary} />
        </div>
      </DrawerContent>
    </Drawer>
  );
}

export function WeeklyReportBody({ summary }: { summary: ReportSummary }) {
  const { revenue, profit, fastestSelling, dailySales, lowStock, maxAmount, bestDay, slowestDay, profitMargin } = summary;

  return (
    <div className="space-y-4">
      <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
        This Week
      </p>

      <div className="grid grid-cols-2 gap-3">
        <div className="rounded-sm border border-border bg-card p-4">
          <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
            Revenue
          </p>
          <h3 className="mt-1 font-mono text-xl font-black text-foreground">
            ₦{revenue.toLocaleString()}
          </h3>
          {revenue > 0 && (
            <span className="mt-1 flex items-center gap-0.5 text-[11px] font-bold text-emerald-600">
              <TrendUp weight="fill" className="h-3.5 w-3.5" />
              this week
            </span>
          )}
        </div>

        <div className="rounded-sm border border-border bg-card p-4">
          <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
            Profit
          </p>
          <h3 className="mt-1 font-mono text-xl font-black text-foreground">
            ₦{profit.toLocaleString()}
          </h3>
          <span className={`mt-1 flex items-center gap-0.5 text-[11px] font-bold ${profitMargin >= 20 ? "text-emerald-600" : "text-rose-500"}`}>
            {profitMargin >= 20 ? <TrendUp weight="fill" className="h-3.5 w-3.5" /> : <TrendDown weight="fill" className="h-3.5 w-3.5" />}
            {profitMargin}% margin
          </span>
        </div>
      </div>

      {dailySales.length > 0 && (
        <div className="rounded-sm border border-border bg-card p-4">
          <h4 className="mb-3 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
            Daily Sales Pattern
          </h4>
          <div className="flex items-end justify-between gap-1 px-1">
            {dailySales.map((bar, idx) => {
              const barH = maxAmount > 0 ? (bar.amount / maxAmount) * 72 : 0;
              const isBest = bestDay && bar.day === bestDay.day;
              return (
                <div key={idx} className="flex flex-1 flex-col items-center">
                  <span className="mb-1 text-[8px] font-bold text-muted-foreground">
                    ₦{bar.amount > 1000 ? `${Math.round(bar.amount / 1000)}k` : bar.amount}
                  </span>
                  <div
                    className={`w-full max-w-[28px] rounded-t-full transition-all ${
                      isBest
                        ? "bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.3)]"
                        : "bg-border"
                    }`}
                    style={{ height: barH }}
                  />
                  <span
                    className={`mt-1.5 text-[10px] font-bold ${
                      isBest ? "text-emerald-600" : "text-muted-foreground"
                    }`}
                  >
                    {bar.day}
                  </span>
                </div>
              );
            })}
          </div>

          {bestDay && slowestDay && bestDay.day !== slowestDay.day && (
            <div className="mt-4 rounded-sm bg-secondary p-3">
              <p className="text-[11px] leading-relaxed text-muted-foreground">
                <span className="font-bold text-foreground">
                  Your busiest day was {dayName(bestDay.day)}
                </span>{" "}
                with ₦{bestDay.amount.toLocaleString()} in sales.{" "}
                {dayName(slowestDay.day)} was the slowest
                with ₦{slowestDay.amount.toLocaleString()}.
              </p>
            </div>
          )}
        </div>
      )}

      {revenue > 0 && (
        <div className="rounded-sm border border-border bg-card p-4">
          <h4 className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
            Revenue vs Profit Breakdown
          </h4>
          <div className="space-y-2.5">
            <div>
              <div className="mb-1 flex items-center justify-between text-[11px]">
                <span className="font-semibold text-foreground">Revenue</span>
                <span className="font-mono font-bold text-foreground">
                  ₦{revenue.toLocaleString()}
                </span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
                <div className="h-full rounded-full bg-emerald-500" style={{ width: "100%" }} />
              </div>
            </div>
            <div>
              <div className="mb-1 flex items-center justify-between text-[11px]">
                <span className="font-semibold text-foreground">Profit</span>
                <span className="font-mono font-bold text-foreground">
                  ₦{profit.toLocaleString()}
                </span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
                <div className="h-full rounded-full bg-primary" style={{ width: `${profitMargin}%` }} />
              </div>
            </div>
          </div>
          <p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">
            You kept <span className="font-bold text-foreground">{profitMargin}%</span> of your
            revenue as profit this week. That's a healthy margin for a retail shop. Keep watching
            your cost prices to maintain or grow this.
          </p>
        </div>
      )}

      {fastestSelling && (
        <div className="flex items-center justify-between rounded-sm border border-emerald-200 bg-emerald-50 p-4">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-sm bg-emerald-100 text-emerald-600">
              <Package weight="fill" className="h-4 w-4" />
            </div>
            <div>
              <p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">
                Fastest Selling
              </p>
              <p className="mt-0.5 text-xs font-bold text-foreground">
                {fastestSelling.product_name}
              </p>
            </div>
          </div>
          <span className="rounded-full bg-emerald-600 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-white">
            Top Seller
          </span>
        </div>
      )}

      {lowStock.length > 0 && (
        <div className="rounded-sm border border-amber-200 bg-amber-50 p-4">
          <p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-amber-700">
            Low Stock Alert
          </p>
          <div className="space-y-1.5">
            {lowStock.map((item, idx) => (
              <div key={idx} className="flex items-center justify-between text-[11px]">
                <span className="font-semibold text-foreground">{item.product_name}</span>
                <span className="font-bold text-amber-700">{item.quantity} left</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {revenue === 0 && (
        <div className="rounded-sm border border-dashed border-border p-8 text-center">
          <ChartLineUp weight="duotone" className="mx-auto mb-2 h-8 w-8 text-muted-foreground" />
          <p className="text-xs font-bold text-foreground">No data yet</p>
          <p className="mt-1 text-[11px] text-muted-foreground">
            Start recording sales to see your weekly report here.
          </p>
        </div>
      )}
    </div>
  );
}

export function WeeklyReportFooter({ summary }: { summary: ReportSummary }) {
  return (
    <div className="flex gap-2">
      <Button
        variant="outline"
        className="flex-1 cursor-pointer gap-1.5 border-rose-200 py-3 text-xs font-bold uppercase tracking-wider text-rose-600 hover:bg-rose-50 hover:text-rose-700"
      >
        <FilePdf weight="fill" className="h-4 w-4 text-rose-500" />
        Save PDF
      </Button>
      <Button
        asChild
        className="flex-1 cursor-pointer gap-1.5 bg-[#25D366] py-3 text-xs font-bold uppercase tracking-wider text-white hover:bg-[#128C7E]"
      >
        <a href={summary.shareUrl} target="_blank" rel="noopener noreferrer">
          <WhatsappLogo weight="fill" className="h-4 w-4" />
          Share
        </a>
      </Button>
    </div>
  );
}
